// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
/*using System;
using NUnit.Framework;

using UnityEngine;
using UnityEditor;

namespace AssemblyCSharpEditor
{
	[TestFixture()]
	public class BetweenTest
	{
		[Test()]
		public void TestCase ()
		{
			float value = 5;
			float a = 1;
			float b = 10;
			
			bool result = Utils.CustomBetween (value, a, b);
			Assert.AreEqual (result, true);
		}
	}
}
*/